name : deepward
version : 0.0.1
# server敲门
TUN:
    IP: 10.0.0.30
    PORT: 9826
    ALLOW_IP: 192.168.3.51
    ALLOW_PORT: "*"
    PRK: xDuiZavqIr1UlBeLHCPEsytZoC0JAqRnmF+o0NP2hxI=

PEER:
    PORT: 50879
    IP: 124.193.68.147
    PUK: BN6vEfnXVeqF7ry1oarKBLQ7kCDG7hrkVCv9rDgPv8genRMosu/y+Ow9770X0rOLzFEjEuJfN6WyHEq+yDarcnU=
